### PR TITLE
Fix #907 - mill-contrib-playlib: java.lang.NoClassDefFoundError

### LINKED ISSUE #907: mill-contrib-playlib: java.lang.NoClassDefFoundError: mill/playlib/api/RouteCompilerWorkerApi
```
mill.scalalib.GenIdea.idea java.lang.NoClassDefFoundError: mill/playlib/api/RouteCompilerWorkerApi
    java.lang.ClassLoader.defineClass1(Native Method)
    java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    java.security.AccessController.doPrivileged(Native Method)
    java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:23)
    java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    mill.playlib.RouteCompilerWorker.bridge(RouteCompilerWorkerApi.scala:27)
    mill.playlib.RouteCompilerWorker.compile(RouteCompilerWorkerApi.scala:48)
    mill.playlib.RouterModule.$anonfun$compileRouter$2(RouterModule.scala:62)
    mill.define.ApplyerGenerated.$anonfun$zipMap$3(ApplicativeGenerated.scala:9)
    mill.define.Task$MappedDest.evaluate(Task.scala:392)
    mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:476)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withErr(Console.scala:193)
    mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:476)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withOut(Console.scala:164)
    mill.eval.Evaluator.$anonfun$evaluateGroup$11(Evaluator.scala:475)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withIn(Console.scala:227)
    mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:474)
    mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:426)
    scala.collection.immutable.Vector.foreach(Vector.scala:1794)
    mill.eval.Evaluator.evaluateGroup(Evaluator.scala:426)
    mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:329)
    mill.eval.Evaluator.$anonfun$sequentialEvaluate$2(Evaluator.scala:110)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
    scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
    mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:93)
    mill.eval.Evaluator.evaluate(Evaluator.scala:79)
    mill.scalalib.GenIdeaImpl.$anonfun$xmlFileLayout$90(GenIdeaImpl.scala:379)
    scala.collection.immutable.Vector1.map(Vector.scala:1824)
    scala.collection.immutable.Vector1.map(Vector.scala:348)
    mill.scalalib.GenIdeaImpl.xmlFileLayout(GenIdeaImpl.scala:373)
    mill.scalalib.GenIdeaImpl.run(GenIdeaImpl.scala:36)
    mill.scalalib.GenIdea$.$anonfun$idea$2(GenIdea.scala:14)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

### PR DESCRIPTION
**Pull request by imxieshuang**
This PR fix mill/playlib/api/RouteCompilerWorkerApi Class not found.
Resolves #907

### CODE REVIEW

**Comment by lefou** [comment]
Tests are failing. One issue:

```
 X mill.playlib.RouterModuleTests.compileRouter invalid sub.routes  137ms 
  java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    mill.playlib.worker.RouteCompilerWorker.compile(RouteCompilerWorker.scala:24)
    mill.playlib.RouteCompilerWorker.compile(RouteCompilerWorkerApi.scala:56)
    mill.playlib.RouterModule.$anonfun$compileRouter$2(RouterModule.scala:72)
    mill.define.ApplyerGenerated.$anonfun$zipMap$3(ApplicativeGenerated.scala:9)
    mill.define.Task$MappedDest.evaluate(Task.scala:391)
    mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:491)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withErr(Console.scala:193)
    mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:491)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withOut(Console.scala:164)
    mill.eval.Evaluator.$anonfun$evaluateGroup$11(Evaluator.scala:490)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withIn(Console.scala:227)
    mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:489)
    mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:441)
    scala.collection.immutable.Vector.foreach(Vector.scala:1794)
    mill.eval.Evaluator.evaluateGroup(Evaluator.scala:441)
    mill.eval.Evaluator.$anonfun$evaluateGroupCached$13(Evaluator.scala:343)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:334)
    mill.eval.Evaluator.$anonfun$sequentialEvaluate$2(Evaluator.scala:117)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
    scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
    mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:94)
    mill.eval.Evaluator.evaluate(Evaluator.scala:80)
    mill.util.TestEvaluator.apply(TestEvaluator.scala:53)
    mill.playlib.RouterModuleTests$.$anonfun$tests$22(RouterModuleTests.scala:102)
    mill.playlib.RouterModuleTests$.$anonfun$tests$22$adapted(RouterModuleTests.scala:101)
    mill.playlib.RouterModuleTests$.workspaceTest(RouterModuleTests.scala:45)
    mill.playlib.RouterModuleTests$.$anonfun$tests$21(RouterModuleTests.scala:48)
```

Also, it would be helpful if you provide some information/description of your fix.

**Comment by imxieshuang** [comment]
Your error should be that the play version is 2.6. If the play version is 2.7, there will be no such error.
Because the Scala version of mill is 2.13, the Scala version of play-routes-compiler also needs to be 2.13, but play2.6 does not support 2.13

**Comment by lefou** [comment]
The play routes compiler should not depend on the Scala version mill is using. After all, we can compile any version of Scala. That's also the point of not sharing classes other that from Java core and the worker api which is pure Java. But your change seems to enable more sharing. That's why I requested a description / motivation of your change.

**Comment by lefou** [comment]
Closing due to lack of response and activity.

**Pull request closed without merging**
