### PR TITLE
Use mill examples in init

### PR DESCRIPTION
**Pull request by pawelsadlo**
implements #3548 
Modifying init to fetch examples from releases page instead of using g8 template

This introduces new top-level module `initmodule`
this module generates resource `exampleList.txt` containing json with array of pairs `(exampleId,exampleUrl)`
`exampleId` and `exampleUrl` are formed based on already present `exampleZips` target, and `millVersion()`.

initmodule introduces external module `MillInitModule`
calls to` mill init ` are redirected to `MillInitModule.init` (basically the same logic as it was with `Giter8Module.init`)

`MillInitModule.init` called without parameters prints message containing `exampleids` list based on generated exampleList.txt in the form of:

```
Run init with one of the following examples as an argument to download and extract example:
depth/cross/1-simple
depth/cross/2-cross-source-path
...
```
When called with a parameter it validates if passed parameter is in the list, and if so, it downloads example from github releases page and unpacks it into the directory from where the command was run.

### CODE REVIEW

**Comment by pawelsadlo2** [comment]
@lihaoyi I have added some integration tests which tries to download examples from GitHub repo, 
They are working locally but failing on Ci, i assume that CI can't access internet right?

**Comment by lihaoyi** [comment]
CI should be able to access the internet, not sure why it's failing

**Comment by pawelsadlo** [comment]
I have found the issue, I was relying on millVersion target to build download URLs.

But nor millVersion, neither millLastTag targets returns valid versions when runned on CI.

Is there any reliable function that return last released mill version already implemented in codebase?

**Comment by lihaoyi** [comment]
@pawelsadlo I think for the purposes of this ticket, let's skip end-to-end tests that download from Github. Those are inherently non-hermetic and we don't have the infrastructure to stand up test github instances to make them hermetic. Smaller unit tests for the various pieces of logic, and manually exercising the end to end workflow, should be enough for now

**Comment by pawelsadlo** [comment]
@lihaoyi, could you review, please?

**Comment by lihaoyi** [comment]
@pawelsadlo could you update the PR description with a summary of the changes and anything worth taking note of? That would make the review easier

**Comment by pawelsadlo** [comment]
@lihaoyi I have updated the description

**Comment by lihaoyi** [comment]
Thanks! will take a look tomorrow

**Comment by lihaoyi** [comment]
I think this looks good. Some thoughts:

1. Can we improve the UX of the CLI message? e.g. adding the `mill init` command for people to reference
```
Run `mill init <example-id>` with one of the following examples as an argument to download and extract example:
```

2. I expect that for a lot of people and terminals, the list of examples is large enough that the instructions are pushed off screen, which is confusing. Maybe we can duplicate the `Run ...` message below the list as well, so the instructions are always visible in the terminal after running?

Screenshot 2024-09-25 at 7 57 22 AM

3. What happens if we run `mill init` in a folder that already has stuff? Does it fail, does it over-write, or does it merge the example with the current files? I would assume it should fail

4. Can we keep the older Giter8 codepath working? e.g. allow both an example from this list OR a giter8 URL, and just do the right thing depending on what is passed. This should be mentioned in the instruction message

5. The stuff in the `example/` folder is of varying degrees of relevance, so let's display a short-list of most-likely-relevant examples to the user:
    * `langlib/basic/*`, `langlib/builds/*`, `langlib/web/*`are probably the most relevant for anyone who would be using `init to get started with a new Mill project.
    * We can hide the full list behind a `--show-all` flag (included in the instruction message) in case anyone wants to see the others

**Comment by pawelsadlo** [comment]
@lihaoyi 
coded in your suggestions:

Ad1.
Message displayed is:
```
Run `mill init <example-id>` with one of the following examples as an argument to download and extract example.
Run `mill init --show-all` to see full list of examples.
Run `mill init <Giter8 template>` to generate project from Giter8 template.
```

Ad2.
Done

Ad3.
now it fails with error: 
```
Can't download example, because extraction directory [/Users/psadlo/Desktop/millInitTest/0.12.0-RC2-example-scalalib-basic-1-simple] already exist
1 targets failed
init java.lang.Exception: 1 targets failed
mill.initmodule.InitModule.init java.io.IOException: Can't download example, because extraction directory [/Users/psadlo/Desktop/millInitTest/0.12.0-RC2-example-scalalib-basic-1-simple] already exist
    mill.initmodule.InitModule.$anonfun$init$10(InitModule.scala:62)
    scala.util.Success.flatMap(Try.scala:266)
    mill.initmodule.InitModule.$anonfun$init$3(InitModule.scala:52)
    mill.initmodule.InitModule.$anonfun$usingExamples$2(InitModule.scala:95)
    scala.util.Using$.apply(Using.scala:296)
    mill.initmodule.InitModule.usingExamples(InitModule.scala:92)
    mill.initmodule.InitModule.$anonfun$init$2(InitModule.scala:36)
    mill.main.MainModule.$anonfun$init$2(MainModule.scala:426)
```

Ad4.
If first arg ends with `.g8`, we fallback to g8 initialization now.

Ad5.
This is what is now displayed when called `mill init`

```
Run `mill init <example-id>` with one of the following examples as an argument to download and extract example.
Run `mill init --show-all` to see full list of examples.
Run `mill init <Giter8 template>` to generate project from Giter8 template.

scalalib/basic/1-simple
scalalib/basic/2-custom-build-logic
scalalib/basic/3-multi-module
scalalib/basic/4-builtin-commands
scalalib/basic/5-multiple-test-frameworks
scalalib/builds/1-common-config
scalalib/builds/2-custom-tasks
scalalib/builds/3-override-tasks
scalalib/builds/4-nested-modules
scalalib/builds/7-cross-scala-version
scalalib/builds/8-compat-modules
scalalib/builds/9-realistic
scalalib/web/1-todo-webapp
scalalib/web/2-webapp-cache-busting
scalalib/web/3-scalajs-module
scalalib/web/4-webapp-scalajs
scalalib/web/5-webapp-scalajs-shared
scalalib/web/6-cross-version-platform-publishing
scalalib/web/7-cross-platform-version-publishing
javalib/basic/1-simple
javalib/basic/2-custom-build-logic
javalib/basic/3-multi-module
javalib/basic/4-builtin-commands
javalib/builds/1-common-config
javalib/builds/2-custom-tasks
javalib/builds/3-override-tasks
javalib/builds/4-nested-modules
javalib/builds/8-compat-modules
javalib/builds/9-realistic
javalib/web/1-hello-jetty
javalib/web/2-hello-spring-boot
javalib/web/3-todo-spring-boot
javalib/web/4-hello-micronaut
javalib/web/5-todo-micronaut
kotlinlib/basic/1-simple
kotlinlib/basic/2-custom-build-logic
kotlinlib/basic/3-multi-module
kotlinlib/basic/4-builtin-commands

Run `mill init <example-id>` with one of the following examples as an argument to download and extract example.
Run `mill init --show-all` to see full list of examples.
Run `mill init <Giter8 template>` to generate project from Giter8 template.
```

This is displayed when runned `mill init --show-all`

```
Run `mill init <example-id>` with one of the following examples as an argument to download and extract example.
Run `mill init --show-all` to see full list of examples.
Run `mill init <Giter8 template>` to generate project from Giter8 template.

scalalib/basic/1-simple
scalalib/basic/2-custom-build-logic
scalalib/basic/3-multi-module
scalalib/basic/4-builtin-commands
scalalib/basic/5-multiple-test-frameworks
scalalib/builds/1-common-config
scalalib/builds/2-custom-tasks
scalalib/builds/3-override-tasks
scalalib/builds/4-nested-modules
scalalib/builds/7-cross-scala-version
scalalib/builds/8-compat-modules
scalalib/builds/9-realistic
scalalib/web/1-todo-webapp
scalalib/web/2-webapp-cache-busting
scalalib/web/3-scalajs-module
scalalib/web/4-webapp-scalajs
scalalib/web/5-webapp-scalajs-shared
scalalib/web/6-cross-version-platform-publishing
scalalib/web/7-cross-platform-version-publishing
scalalib/linting/1-scalafmt
scalalib/module/1-compilation-execution-flags
scalalib/module/2-ivy-deps
scalalib/module/3-run-compile-deps
scalalib/module/5-resources
scalalib/module/6-scala-compiler-plugins
scalalib/module/7-docjar
scalalib/module/8-unmanaged-jars
scalalib/module/9-main-class
scalalib/module/10-downloading-non-maven-jars
scalalib/module/11-assembly-config
scalalib/module/12-repository-config
scalalib/module/13-contrib-scoverage
scalalib/module/14-unidoc
scalalib/publishing/2-publish-module
scalalib/testing/1-test-suite
scalalib/testing/2-test-deps
scalalib/testing/3-integration-suite
javalib/basic/1-simple
javalib/basic/2-custom-build-logic
javalib/basic/3-multi-module
javalib/basic/4-builtin-commands
javalib/builds/1-common-config
javalib/builds/2-custom-tasks
javalib/builds/3-override-tasks
javalib/builds/4-nested-modules
javalib/builds/8-compat-modules
javalib/builds/9-realistic
javalib/web/1-hello-jetty
javalib/web/2-hello-spring-boot
javalib/web/3-todo-spring-boot
javalib/web/4-hello-micronaut
javalib/web/5-todo-micronaut
javalib/linting/1-error-prone
javalib/linting/2-checkstyle
javalib/module/1-compilation-execution-flags
javalib/module/2-ivy-deps
javalib/module/3-run-compile-deps
javalib/module/5-resources
javalib/module/6-annotation-processors
javalib/module/7-docjar
javalib/module/8-unmanaged-jars
javalib/module/9-main-class
javalib/module/10-downloading-non-maven-jars
javalib/module/11-assembly-config
javalib/module/12-repository-config
javalib/module/13-jni
javalib/publishing/2-publish-module
javalib/testing/1-test-suite
javalib/testing/2-test-deps
javalib/testing/3-integration-suite
kotlinlib/basic/1-simple
kotlinlib/basic/2-custom-build-logic
kotlinlib/basic/3-multi-module
kotlinlib/basic/4-builtin-commands
extending/imports/3-import-ivy
extending/imports/6-contrib-import
extending/metabuild/4-meta-build
extending/metabuild/5-meta-shared-sources
extending/plugins/7-writing-mill-plugins
external/libraries/1-oslib
external/libraries/2-upickle
external/libraries/3-requests
external/libraries/4-mainargs
depth/cross/1-simple
depth/cross/2-cross-source-path
depth/cross/3-outside-dependency
depth/cross/4-cross-dependencies
depth/cross/5-multiple-cross-axes
depth/cross/6-axes-extension
depth/cross/7-inner-cross-module
depth/cross/8-resolvers
depth/cross/9-dynamic-cross-modules
depth/cross/10-static-blog
depth/cross/11-default-cross-module
depth/large/10-multi-file-builds
depth/large/11-helper-files
depth/large/12-helper-files-sc
depth/large/13-helper-files-mill-scala
depth/modules/7-modules
depth/modules/8-diy-java-modules
depth/modules/9-backticked-names
depth/sandbox/1-task
depth/sandbox/2-test
depth/sandbox/3-breaking
depth/tasks/1-task-graph
depth/tasks/2-primary-tasks
depth/tasks/3-anonymous-tasks
depth/tasks/4-inputs
depth/tasks/5-persistent-targets
depth/tasks/6-workers
depth/tasks/11-module-run-task
thirdparty/acyclic
thirdparty/commons-io
thirdparty/fansi
thirdparty/gatling
thirdparty/jimfs
thirdparty/mockito
thirdparty/netty

Run `mill init <example-id>` with one of the following examples as an argument to download and extract example.
Run `mill init --show-all` to see full list of examples.
Run `mill init <Giter8 template>` to generate project from Giter8 template.
```

**Comment by lihaoyi** [comment]
@pawelsadlo a few more nits and I think we're done:

1. `with one of the following examples` should probably just be `with one of these examples`, since it appears below the list of examples as well
2. I find the message `Can't download example, because extraction directory [...] already exist` a bit confusing. Isn't `mill init` meant to download and extract the given zip into the current directory, which should already exist? Or does it extract into a subfolder? What does giter8 do? Also let's add a unit test to this failure case
3. The short list of examples should also include `kotlinlib/builds`

**Comment by pawelsadlo** [comment]
@lihaoyi 
Ad1. done
Ad2 -
it extracts into subfolder - this exception is thrown if there is already an existing subfolder with the same name
g8 also extracts to subfolder, however it merges folders recursively if there is already existing one

do you have any better error msg in mind?

will add test shortly.

Ad3 - its working as expected, I just didnt update repo locally.

**Comment by pawelsadlo** [comment]
@lihaoyi 
I have implemented every suggestion, however there is a problem

link to example is of the form:
`<millRepo>/releases/download/<millLastTag()>/<millVersion()>-example-depth-cross-2-cross-source-path.zip`

but <millLastTag()> is failing on CI

so what is coded now is millVersion() instead of millLastTag()
`<millRepo>/releases/download/<millVersion()>/<millVersion()>-example-depth-cross-2-cross-source-path.zip`

but this forms malformed links for current version
`<millRepo>/releases/download/0.12.0-RC2-38-029986/0.12.0-RC2-38-029986-example-depth-cross-2-cross-source-path.zip`

instead of:
`<millRepo>/releases/download/0.12.0-RC2/0.12.0-RC2-38-029986-example-depth-cross-2-cross-source-path.zip`

Is this a big problem to have it wrong in RC version (assuming that in release it will be fixed)?
is there any tool to know that mill is being build on CI?

if its a big problem we can always manually get tag from millVersion() by parsing the string (this would remove millLastTag() call)

**Comment by lihaoyi** [comment]
@pawelsadlo I'd be OK parsing `millVersion()`. I'm a bit curious how come `millLastTag` fails in CI when `millVersion()` doesn't, as I would expect both to end up calling the same underlying Git APIs

**Comment by pawelsadlo** [comment]
> @pawelsadlo I'd be OK parsing `millVersion()`. I'm a bit curious how come `millLastTag` fails in CI when `millVersion()` doesn't, as I would expect both to end up calling the same underlying Git APIs. Maybe @lefou knows?
> 
There is just a hard coded fallback to 0.0.0 on mill version targer.

> Mill on Github Actions should have the `CI=true` environment variable set, according to the docs https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables, so we should be able to check for that as well

I was trying this, but it didn't work.

**Comment by lihaoyi** [comment]
Thanks @pawelsadlo, give me some time to tinker around with the PR and I think we can merge it.

**Comment by pawelsadlo** [comment]
Sure , take your time

**Comment by lihaoyi** [comment]
Looks good to me, i'll continue tinkering with it post-merge. @pawelsadlo will send the bank transfer using the same details as before

**Comment by pawelsadlo** [comment]
@lihaoyi 
I have added one more PR taking milestones into account when parsing millLastTag from millVersion #3625

**Comment by bishabosha** [comment]
was there a specific reason why the codesig object was moved to its own package.mill?

**Pull request merged**
