### PR TITLE
Mask colons in segment paths

### PR DESCRIPTION
**Pull request by lefou**
Again a Windows thing, but the evaluator paths should not contain colons. We mask them with `$colon`.

Fix https://github.com/com-lihaoyi/mill/pull/2923

### CODE REVIEW

**Comment by lihaoyi** [comment]
Since we're escaping things with `$`, should we also mask `$` with `$$` to avoid potential conflicts?

**Comment by lefou** [comment]
> Since we're escaping things with `$`, should we also mask `$` with `$$` to avoid potential conflicts?

Can you a bit more specific. What do we mask with `$` and which conflicts do you expect with this concrete `$colon`?

**Comment by lefou** [comment]
@lihaoyi Did you mean the name mangling for private inner classes in Scala? Or something else?

I think the masking I introduce here doesn't need to be bijective. It's only from segment path to file path. So, the question is, will two different segment paths project to the same file path?

**Comment by lihaoyi** [comment]
@lefou oh I wasn't thinking about Scala compiler name mangling, I was more thinking about potential collisions caused by Mill's own mangling. Like if we have two tasks, with names `a:b` and `a$colonb`, they would collide unless we escaped the `$` such that `a$colonb` becomes `a$$colonb`

This isn't an edge case likely to cause any issues in practice, but it's definitely a thing

**Pull request merged**
