### PR TITLE
Update coursier to 2.0.16+73-gddc6d9cc9

### PR DESCRIPTION
**Pull request by alexarchambault**
On Windows, this should fix some issues where trying to access the coursier cache blocks indefinitely.

### CODE REVIEW

**Comment by lefou** [comment]
Can you provide any link to an issue or pull request with more details?

**Comment by alexarchambault** [comment]
@lefou That's mainly to benefit from https://github.com/coursier/coursier/pull/2025. On my personal Windows machine, recent versions of Mill get stuck when coursier tries to compute its cache directory. https://github.com/coursier/coursier/pull/2025 is meant to address that. I'm not sure when or why this issue happens (it's not been a problem on GitHub actions Windows workers for example).

**Review by lefou — APPROVED** [review]
Looks good to me. Thank you! But I need to find out, why some tests now fail on Windows. Unrelated to this pull request I think, but still it fails the build and publish pipeline. I understand the error, but not why it fails now but not before. Maybe, the GH images have changed.

**Comment by lefou** [comment]
I don't know why only this PR fails but not others. But I have identified the path logic incosistency in this test compared to the GenIdeaImpl logic and create another PR to fix it: #1466 .

**Comment by alexarchambault** [comment]
That might be because the coursier cache path calculation changed (no more `null` with this coursier version), which makes it land in a different drive in these Windows jobs.

**Pull request merged**
