### PR TITLE
Fix InvalidPathException using BSP on Windows.

### PR DESCRIPTION
**Pull request by Iltotore**
- Fix invalid windows path produced by `URL#getFile` in `mill.bsp.ModuleUtils#getMillBuildClasspath`, fixing #1091 and #1021

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Looks reasonable. I'd would be great, to also have a test case for that.

**Comment by Iltotore** [comment]
> Looks reasonable. I'd would be great, to also have a test case for that.

Yes. Paths can be capricious between opération systems.

**Comment by lefou** [comment]
> > Looks reasonable. I'd would be great, to also have a test case for that.
> 
> Yes. Paths can be capricious between operating systems. Maybe this test and change should be applied to the oslib.

Are you going to create a PR for oslib?

**Comment by Iltotore** [comment]
> > > Looks reasonable. I'd would be great, to also have a test case for that.
> > 
> > 
> > Yes. Paths can be capricious between operating systems. Maybe this test and change should be applied to the oslib.
> 
> @Iltotore Are you going to create a PR for oslib?

If you think it is better than pushing changes here, yes.

**Comment by lefou** [comment]
It's a misbehavior there and should be fixed there.

**Comment by lefou** [comment]
Superseded by https://github.com/com-lihaoyi/mill/pull/1285 and also by upstream PR https://github.com/com-lihaoyi/os-lib/pull/53.

**Comment by lefou** [comment]
@Iltotore Thank you for your work on this topic! Although we fixed the issue now without any of your commits, your work is highly appreciated.

**Pull request closed without merging**
