### PR TITLE
JMH Plugin: Part deux

### PR DESCRIPTION
**Pull request by Quafadas**
I think the previous solution, actually did work. However, something itched at me. 

After a night sleep, I've realised that I don't think it correctly follows mills nomenclature. `--add-modules=jdk.incubator.vector` is a JVM init flag, _not_ (I believe) a compiler flag. Hence, I think this really belongs in the "forkArgs" task. 

The previous solution works, because both are a list of strings in the end, but I think this revised version more correctly follows mill nomenclature. Apologies for the spamminess. I couldn't see it before somehow. 

> Oh I meant that you could use it for manual testing: it generates a local mill binary with all thee stuff publishLocaled for you to try out. But if the override works in your local build, I think that's enough confidence for me

I didn't realise this was possible - for me thought it provides a scary looking compiler error. I've had this with mill before - my previous contributions have been made through bootlegging this proposal #3108 , as I couldn't get mill to compile locally;

```
02 Publishing Artifact(com.lihaoyi,mill-main-server_2.13,0.10.1-1360-78b0b7) to ivy repo /Users/simon/.ivy2/local
#01 [warn] /Users/simon/Code/mill-1/scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala:524:43: method getId in class Thread is deprecated (since 19)
#01 [warn]     val loggerId = Thread.currentThread().getId.toString
#01 [warn]                                           ^
#07 [error] 
#07 [error]   bad constant pool index: 0 at pos: 49176
#07 [error]      while compiling: <no file>
#07 [error]         during phase: globalPhase=<no phase>, enteringPhase=<some phase>
#07 [error]      library version: version 2.13.8
#07 [error]     compiler version: version 2.13.8
#07 [error]   reconstructed args: -deprecation -feature -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -Wunused:imports -Wunused:privates -Wunused:locals -Wunused:implicits -Wunused:nowarn -Xlint:adapted-args -Xlint:unused -classpath /Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scoverage/scalac-scoverage-plugin_2.13.8/1.4.11/scalac-scoverage-plugin_2.13.8-1.4.11.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.10.7/os-lib_2.13-0.10.7.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mainargs_2.13/0.7.4/mainargs_2.13-0.7.4.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle_2.13/3.3.1/upickle_2.13-3.3.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.9.0/pprint_2.13-0.9.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.5.0/fansi_2.13-0.5.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.11.0-M2/mill-moduledefs_2.13-0.11.0-M2.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/1.3.0/scala-xml_2.13-1.3.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.1/geny_2.13-1.1.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.12.0/scala-collection-compat_2.13-2.12.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/ujson_2.13/3.3.1/ujson_2.13-3.3.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upack_2.13/3.3.1/upack_2.13-3.3.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.13/3.3.1/upickle-implicits_2.13-3.3.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.4.0/sourcecode_2.13-0.4.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.8/scala-compiler-2.13.8.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/kohlschutter/junixsocket/junixsocket-native-common/2.10.0/junixsocket-native-common-2.10.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/kohlschutter/junixsocket/junixsocket-common/2.10.0/junixsocket-common-2.10.0.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.13/3.3.1/upickle-core_2.13-3.3.1.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.8/scala-reflect-2.13.8.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.26.3/jline-3.26.3.jar:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/Users/simon/Code/mill-1/contrib/scoverage/api/compile-resources:/Users/simon/Code/mill-1/out/contrib/scoverage/api/compile.dest/classes:/Users/simon/Code/mill-1/main/api/compile-resources:/Users/simon/Code/mill-1/out/main/api/compile.dest/classes:/Users/simon/Code/mill-1/main/client/compile-resources:/Users/simon/Code/mill-1/out/main/client/compile.dest/classes:/Users/simon/Code/mill-1/contrib/scoverage/worker/compile-resources:/Users/simon/Code/mill-1/out/contrib/scoverage/worker/compile.dest/classes -Xplugin:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/acyclic_2.13.8/0.3.12/acyclic_2.13.8-0.3.12.jar -Xplugin:/Users/simon/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.8/0.11.0-M2/scalac-mill-moduledefs-plugin_2.13.8-0.11.0-M2.jar -P:acyclic:force

```

### CODE REVIEW

**Comment by lihaoyi** [comment]
@Quafadas I think this looks great, if you resolve the conflicts I'll merge it

**Comment by lihaoyi** [comment]
Closing this out of inactivity. Feel free to re-open if necessary

**Comment by Quafadas** [comment]
I've just come back from a few weeks afk. 

I'll try and rebase / resolve it in the coming days. Apologies for the delay.

**Comment by Quafadas** [comment]
Rebased - apologies for the delay.

**Comment by Quafadas** [comment]
Aw hell, I looked at the PR diff, and apparently it's now advertising all the change made in the _rebase_ onto main. Not just mine. TIL. 

Would I better off closing and reopening this? Seems to be a mess.

**Comment by lihaoyi** [comment]
@Quafadas surr lrt edo that

**Comment by lihaoyi** [comment]
closing due to inactivity. Feel free to open a new squashed PR

**Pull request closed without merging**
