### PR TITLE
Improve Mill plugin classpath exclusions

### PR DESCRIPTION
**Pull request by lefou**
Also refer to transitive modules coordinates in the `BuildInfo.millEmbededDeps` data field.

Added an integration test to make sure it's effectively excluding transitive Mill dependencies.

Fix https://github.com/com-lihaoyi/mill/issues/3207

### CODE REVIEW

**Comment by lolgab** [comment]
There is some commented out code. Is it supposed to be there?

**Comment by lefou** [comment]
> There is some commented out code. Is it supposed to be there?

Kind of. It's the rest of the full transitive dependency chain, which I preserved/snapshot-ed that way. I need to make up my mind, if we need to handle/check them too in the test, or not.

**Comment by lefou** [comment]
> > There is some commented out code. Is it supposed to be there?
> 
> Kind of. It's the rest of the full transitive dependency chain, which I preserved/snapshot-ed that way. I need to make up my mind, if we need to handle/check them too in the test, or not.

I removed them for now.

**Comment by lolgab** [comment]
You can also merge main or rebase

**Review by lolgab — APPROVED** [review]

**Pull request merged**
