### PR TITLE
Add start of Java Web Build Examples page

### PR DESCRIPTION
**Pull request by lihaoyi**
Simple hello-world projects using Spring Boot and Jetty. We can expand it more in future

### CODE REVIEW

**Comment by lihaoyi** [comment]
Not sure why `example.javaweb[1-hello-spring-boot].local.test` passes on my machine and fails in CI. Maybe some kind of mac vs linux thing?

**Comment by lefou** [comment]
> example.javaweb[1-hello-spring-boot].local.test

I get the same error on my Gentoo Linux machine.

```
[2144/2144] example.javaweb[1-hello-spring-boot].local.test 
-------------------------------- Running Tests --------------------------------
/home/lefou/work/opensource/mill/out/example/javaweb/1-hello-spring-boot/local/workspaceDir.dest> 'mill' 'test'
--- Expected output --------
...com.example.HelloSpringBootTest#shouldReturnDefaultMessage() finished...
----------------------------
/home/lefou/work/opensource/mill/out/example/javaweb/1-hello-spring-boot/local/workspaceDir.dest> 'mill' 'runBackground'
--- Expected output --------

----------------------------
/home/lefou/work/opensource/mill/out/example/javaweb/1-hello-spring-boot/local/workspaceDir.dest> 'curl' 'http://localhost:8080'
--- Expected output --------
...<h1>Hello, World!</h1>...
----------------------------
X mill.example.ExampleTestSuite.exampleUsage 23315ms 
  java.util.concurrent.ExecutionException: java.net.ConnectException: Verbindungsaufbau abgelehnt
    java.util.concurrent.FutureTask.report(FutureTask.java:122)
    java.util.concurrent.FutureTask.get(FutureTask.java:205)
    mill.example.ExampleTestSuite$.retryOnTimeout$1(ExampleTestSuite.scala:61)
    mill.example.ExampleTestSuite$.$anonfun$tests$3(ExampleTestSuite.scala:78)
  java.net.ConnectException: Verbindungsaufbau abgelehnt
    sun.nio.ch.Net.pollConnect(Net.java:-2)
    sun.nio.ch.Net.pollConnectNow(Net.java:672)
    sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
    sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
    java.net.Socket.connect(Socket.java:633)
    sun.net.NetworkClient.doConnect(NetworkClient.java:178)
    sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
    sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
    sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
    sun.net.www.http.HttpClient.New(HttpClient.java:386)
    sun.net.www.http.HttpClient.New(HttpClient.java:408)
    sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
    sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
    sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
    sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
    sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1687)
    sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
    java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    requests.Requester$$anon$1.liftedTree1$1(Requester.scala:267)
    requests.Requester$$anon$1.readBytesThrough(Requester.scala:266)
    geny.Readable.writeBytesTo(Writable.scala:93)
    geny.Readable.writeBytesTo$(Writable.scala:93)
    requests.Requester$$anon$1.writeBytesTo(Requester.scala:164)
    requests.Requester.apply(Requester.scala:113)
    mill.example.ExampleTestSuite$.processCommand(ExampleTestSuite.scala:131)
    mill.example.ExampleTestSuite$.processCommandBlock(ExampleTestSuite.scala:106)
    mill.example.ExampleTestSuite$.$anonfun$tests$6(ExampleTestSuite.scala:80)
    mill.example.ExampleTestSuite$.$anonfun$tests$6$adapted(ExampleTestSuite.scala:80)
    scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
    mill.example.ExampleTestSuite$.$anonfun$tests$5(ExampleTestSuite.scala:80)
    mill.example.ExampleTestSuite$.$anonfun$tests$2(ExampleTestSuite.scala:59)
    java.util.concurrent.FutureTask.run(FutureTask.java:264)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    java.lang.Thread.run(Thread.java:840)
Tests: 1, Passed: 0, Failed: 1
1 targets failed
example.javaweb[1-hello-spring-boot].local.test 1 tests failed: 
  mill.example.ExampleTestSuite mill.example.ExampleTestSuite.exampleUsage
```

**Comment by lefou** [comment]
Could be a race condition. Spring takes some while to boot, but runBackground returns before it's finished.

**Comment by lefou** [comment]
We probably need to add `sleep` to the set up supported commands in `ExampleTestSuite`.

**Comment by lihaoyi** [comment]
@lefou you were right, seems its just a matter of github actions runners being slower than my laptop

**Review by lefou — APPROVED** [review]
Looks good to me. Is there a reason you use Spring 2.5.x instead of 3.x? Is it JVM compatibility?

**Comment by lihaoyi** [comment]
@lefou just happened to be the version used in the example I read on someone's blog IIRC

**Pull request merged**
