### PR TITLE
Introduce resolveDepsResult which returns failures correctly

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by lihaoyi** [comment]
We should be able to fix it by properly handling the thrown exception message without changing the API and rewriting all the callsites I think. Unless that proves to be impossible, I think that's definitely the better way to go

**Comment by lolgab** [comment]
So the idea is that when we get an exception during an evaluation, if it's of type `Result.Failure` it behaves as if `Result.Failure` was returned by a `Task` ?

**Comment by lolgab** [comment]
On it :)

**Comment by lolgab** [comment]
Implemented in #3391

**Pull request closed without merging**
