### PR TITLE
Support incremental compilation in Scala Native 0.4.9

### PR DESCRIPTION
**Pull request by lolgab**
Scala Native 0.4.9 added support for this feature: https://github.com/scala-native/scala-native/releases/tag/v0.4.9

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Nice addition. Would be good to seen it working in some test, tough.

**Comment by lolgab** [comment]
> Nice addition. Would be good to seen it working in some test, tough.

I thought about that. Since it doesn't change the binary behaviour, it's hard to assert it's working without assumptions that will probably break on the next version (since it's an experimental feature). Also Scala Native tests are expensive. If you think we need it I can add it. I just manual tested it in scratch.

**Comment by lefou** [comment]
> > Nice addition. Would be good to seen it working in some test, tough.
> 
> I thought about that. Since it doesn't change the binary behaviour, it's hard to assert it's working without assumptions that will probably break on the next version (since it's an experimental feature). Also Scala Native tests are expensive. If you think we need it I can add it. I just manual tested it in scratch.

I see. As I'm not familiar with Scala Native API, I can't tell whether it is easy, possible ,or useless, but maybe we can add some unit test just comparing the expected with the actual used config?

**Comment by lolgab** [comment]
@lefou Added a test that exercises the incremental compilation feature in Scala Native (the `scala.ll` file is created only if you set `nativeIncrementalCompilation = true` otherwise the test fails.

**Review by lefou — APPROVED** [review]
Looks good to me. Thanks for adding the extra test.

I wonder, whether we want to print a warning message, when a feature is enabled but ignored, because of an unsupported version.

**Pull request merged**
