### PR TITLE
Generalize `.runBackground` to work with all kinds of subprocesses

### PR DESCRIPTION
**Pull request by lihaoyi**
Fixes https://github.com/com-lihaoyi/mill/issues/657

We re-use `MillBackgroundWrapper` and extend it to optionally spawn subprocess instead of calling the in-process main method. There's a bit of overhead in the JVM wrapper, but we need some kind of process wrapper to manage the mutex and termination even when the Mill process terminates, and eventually when https://github.com/com-lihaoyi/mill/issues/4007 lands we can use that to provide lighter-weight wrappers. We add a shutdown hook and copy the termination grace-period logic from OS-Lib to try and gently kill the wrapped process when necessary

Integrated this into `PythonModule#runBackground` and added a unit test to verify the asynchronous launch, background existence (by checking that a file lock is taken) and termination on deletion. We can integrate this into `TypescriptModule` as well but punting that for later

The subprocess APIs are a mess but leaving that to fix in 0.13.0 https://github.com/com-lihaoyi/mill/issues/3772

### CODE REVIEW

**Comment by lihaoyi** [comment]
@jodersky do you happen to have a linux environment handy? Somehow `mill.pythonlib.RunBackgroundTests.runBackground` is failing in CI even though it passes on my laptop

**Comment by jodersky** [comment]
I do, in fact it's my main development environment (Debian). I can take a
look at it.

**Comment by lihaoyi** [comment]
thanks!

**Comment by lihaoyi** [comment]
AFAIK the functionality seems to work from manual testing on an EC2 machine, just the test suite which uses a python file-lock to try and check whether the process is alive or not seems to be misbehaving

**Comment by jodersky** [comment]
It's also failing on my machine

```
$ ./mill pythonlib.test mill.pythonlib.RunBackgroundTests.runBackground
X mill.pythonlib.RunBackgroundTests.runBackground 24862ms 
[1335]   java.lang.Exception: File never locked by python subprocess
[1335]     mill.pythonlib.RunBackgroundTests$.sleepIfTimeAvailable$1(RunBackgroundTests.scala:28)
[1335]     mill.pythonlib.RunBackgroundTests$.$anonfun$tests$2(RunBackgroundTests.scala:33)
```

**Comment by jodersky** [comment]
I'm looking into it

**Comment by jodersky** [comment]
I think linux supports multiple file locking mechanisms, so I wonder if this is due to the JVM's `channel.tryLock` not using a `flock()`

**Comment by jodersky** [comment]
I checked the source code, and indeed OpenJDK uses `lockf` rather than `flock`. According to [this stackoverflow answer](https://stackoverflow.com/a/22411531/917519), on FreeBSD and Mac OSX, `lockf` and `flock` interact, but on Linux that is not the case.

Can you try replacing the line containing `flock` with `lockf` in the python script? That change works on my machine, but I don't have access to a mac, so I haven't tested if it also works there.

Alternatively, this should work on all systems
```
        if sys.platform == "linux":
            fcntl.lockf(file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        else:
            fcntl.flock(file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
```

**Comment by lihaoyi** [comment]
@jodersky nice find, let me try that

**Comment by jodersky** [comment]
Unrelated, but have you had any success amending peoples PRs? I can see the check mark "Maintainers are allowed to edit this pull request. ", but when I tried pushing to your branch it was rejected with a "permission denied" error.

**Comment by lihaoyi** [comment]
@jodersky maybe you need repo-specific committer access to amend PRs? So far you only have org-wide committer access, lemme try adding you to the Mill repo

I meant that the main code worked on my EC2 box, the test code failed same as on GHA. I pushed your suggested fix, let's see if it works

**Review by jodersky — APPROVED** [review]

**Pull request merged**
