### PR TITLE
Fix #1283, #1021: Windows BSP: request failed: buildTarget/dependencySources

### LINKED ISSUE #1283: Windows BSP: `request failed: buildTarget/dependencySources` - cannot import into IDE - forward slash is prepended to the paths for some reason
Hi, I installed mill via scoop on my Windows 10 machine, JDK 16; `build.sc` is as follows:

```
import mill._
import scalalib._
object foo extends ScalaModule {
  def scalaVersion = "2.13.5"
}
```

Building with mill works; then I run `mill mill.bsp.BSP/install`, and import the project via IntelliJ's BSP support.

After import, it shows this:
image

I am very keen on mill however last time I tried it it also had some other loading issue (pre-BSP times though iirc).

Stack trace:

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dev/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib_2.13/0.9.6/mill-scalalib_2.13-0.9.6-sources.jar
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:484)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:483)
    at os.Path$.apply(Path.scala:382)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10(ModuleUtils.scala:131)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10$adapted(ModuleUtils.scala:131)
    at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:226)
    at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:221)
    at scala.collection.immutable.ArraySeq.filterImpl(ArraySeq.scala:35)
    at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:217)
    at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:217)
    at scala.collection.immutable.ArraySeq.filter(ArraySeq.scala:35)
    at mill.bsp.ModuleUtils$.getMillBuildClasspath(ModuleUtils.scala:131)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetDependencySources$2(MillBuildServer.scala:136)
    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetDependencySources$1(MillBuildServer.scala:134)
    at mill.bsp.MillBuildServer.handleExceptions(MillBuildServer.scala:495)
    at mill.bsp.MillBuildServer.buildTargetDependencySources(MillBuildServer.scala:129)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    ... 10 more



Apr 18, 2021 6:04:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError

SEVERE: Internal error: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip

java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2178)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
    at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:91)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:831)

Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:484)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:483)
    at os.Path$.apply(Path.scala:382)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10(ModuleUtils.scala:131)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10$adapted(ModuleUtils.scala:131)
    at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:226)
    at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:221)
    at scala.collection.immutable.ArraySeq.filterImpl(ArraySeq.scala:35)
    at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:217)
    at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:217)
    at scala.collection.immutable.ArraySeq.filter(ArraySeq.scala:35)
    at mill.bsp.ModuleUtils$.getMillBuildClasspath(ModuleUtils.scala:131)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetScalacOptions$2(MillBuildServer.scala:394)
    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetScalacOptions$1(MillBuildServer.scala:391)
    at mill.bsp.MillBuildServer.handleExceptions(MillBuildServer.scala:495)
    at mill.bsp.MillBuildServer.buildTargetScalacOptions(MillBuildServer.scala:386)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    ... 10 more

```

### PR DESCRIPTION
**Pull request by ScalaWilliam**
… - cannot import into IDE

There is a PR already (#1092) but I am wary of dealing with Strings directly. Here is my approach.

On Windows, File URLs follow an peculiar representation in Java

```
scala> java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL
java.net.URL = file:/C:/Users/Developer/mill/./
```

From this, we wish to get a `Path` back, and the way to do this is:

```
scala> java.nio.file.Paths.get((java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL).toURI)
java.nio.file.Path = C:\Users\Developer\mill\.
```

Unit testing for this is more challenging because the `WindowsFileSystem` instance is a `sun.nio.fs` package, rather than a standard package.

The solution here, compared to the previous code, is to reduce the number of conversions; the key loss happens when you do `(URL).getFile`.

```
scala> java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL
java.net.URL = file:/C:/Users/Developer/mill/./
scala> java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL.getFile
String = /C:/Users/Developer/mill/./
```

**Other notes:**

I enabled edits by maintainers, and as such please feel free to modify.

**scalafmt**: I was not sure how to apply Scalafmt from Mill as I am very new to this, and my IntelliJ didn't have the option for this imported build to do a scalafmt.

**Testing**: Like #1092, I think unit testing this is very challenging. Are there instructions as to how you could test this, or are you able to do a test of this PR?

I am very pressed for time at the moment, but wanted to make a contribution however my knowledge on this tool is still very limited.

I tried `bsp.test` task, and then import the produced file however this did not work as expected (neither did the original version of mill), where the `mill.json` that is produced looked like:
```
{"name":"mill-bsp","argv":["C:\\Path\\to\\jar1.jar;C:\\Path\\to\jar2.jar...", "-i", ...] }
```

And when importing, it would say that the whole argument is not a file that can be found (rather than the individual files?)

### CODE REVIEW

**Review by lefou — APPROVED** [review]
Thank you for your pull request and the detailed analysis. I also like your solution, to avoid any kind of string mangeling while converting the URL to a path. There is still https://github.com/com-lihaoyi/os-lib/pull/53 which should probably updated to follow the same approach. 

Mill is currently not consistently formatted, so we try to change formatting (according to `.scalafmt.conf`) only for those blocks we touch.

**Comment by ScalaWilliam** [comment]
Thank you for merging this! Looking forward to the next release :-)

**Comment by lefou** [comment]
Yeah, I'm planning a new release soon, but you can already start to use mill snapshot releases containing this fix. See https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html#_overriding_mill_versions

**Comment by camper42** [comment]
after this commit, IDEA on windows & mac both failed on BSP project import

---

with `example-1` project in release
windows` failed with error like `java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\camper42\AppData\Local\Coursier\cache\v1\https\repo.huaweicloud.com\repository\maven\com\lihaoyi\mill-scalalib_2.13\0.9.6-39-99385d\mill-scalalib_2.13-0.9.6-39-99385d-sources.jar`

IDEA
image

bsp-protocol-trace-log
image

maybe `C:\\Users\\camper42\\AppData\\Local\\Coursier\\cache\\v1\\...` should be `file:///C:/Users/camper42/AppData/Local/Coursier/cache/v1/...`

---

on MacOS, import failed with error `java.lang.IllegalArgumentException: Missing scheme`

(I'll apply screenshot later

---

@ScalaWilliam The commit (release 0.9.6-39-99385d) is worked for you, right?

**Pull request merged**
