### PR TITLE
Fixed: #3963 Added Kotlin Spring Boot Example

### PR DESCRIPTION
**Pull request by himanshumahajan138**
# Pull Request 
Added Kotlin Example for Spring Boot 
Fixes: #3963

## Description
Adds Example for Kotlin Spring Boot `6-hello-spring-boot` and `7-todo-spring-boot`

## Related Issues
- Link to related issue #3963.

## Checklist
- [x] New Example For Kotlin Spring Boot Hello World
- [x] New Example for Kotlin Spring Boot Todo MVC

## Status
Completed Addition

### CODE REVIEW

**Comment by himanshumahajan138** [comment]
@lihaoyi i need your guidance 

actually, i had done first part but for second part i want to ask something 

so tell me for the todo mvc application do i need to follow exact the same code as present in the javalib example ?

i  am thinking of adding a good type of setup and including some advanced crud, js and css so is this okay or you want to add something

and i think this will give user a broad view on how to use mill for kotlin spring boot

**Comment by lihaoyi** [comment]
@himanshumahajan138 let's use the exact same Thymeleaf/JS/CSS as the Java example, just to keep things consistent. For people who want more fancy things there's the Ktor and Ktor-KotlinJS examples.

**Comment by himanshumahajan138** [comment]
ok then working on this ✨

**Comment by himanshumahajan138** [comment]
@lihaoyi It's Complete and i didn't played much with documentation part as i followed the way it was present in `javalib/web`

So Let's Finalize this and if anything required, please let me know...

Thanks...

**Comment by lihaoyi** [comment]
Looks good @himanshumahajan138 , I'll close out the bounty

**Pull request merged**
