### PR TITLE
[WIP] make override folders follow the foo.bar output file convention

### PR DESCRIPTION
**Pull request by lihaoyi**
Follow up from https://github.com/com-lihaoyi/mill/pull/1588

### CODE REVIEW

**Comment by lihaoyi** [comment]
Seems to be bumping up against the "Label may not contain a dot" assert. Might take some refactoring in order to resolve that in a non-hacky manner

**Comment by lefou** [comment]
Haha, I did the same change but obviously forgot to push the PR. See #1637

**Comment by lefou** [comment]
I guess this PR is rather a no brainer, it looks good. We should discuss though, why we have the `require` in `Label`. It was an even `assert` before. We have a history regarding this assert/require, see https://github.com/com-lihaoyi/mill/issues/820 and also some non-merged PRs. If it is only to protect from parsing in CLI, maybe we can just ignore it and live with the fact that those labels are probably never used from CLI anyways.

**Comment by lefou** [comment]
@lihaoyi I just wanted to make clear, that it wasn't my intention to make you close your PR, when I pushed my version later. I just wanted to make it visible and start the discussion about the require statement, my interpretation of it and the fact, that all tests pass, once it is removed.

**Comment by lihaoyi** [comment]
@lefou the two PRs are about the same, so happy to go with yours for now

**Pull request closed without merging**
