### PR TITLE
Add search functionality based on @antora/lunr-extension

### PR DESCRIPTION
**Pull request by sake92**
CSS and JS are copied from node_modules, I followed instructions from here https://gitlab.com/antora/antora-lunr-extension  
The index itself is around 600+KB so it doesnt add too much to the site.

This is how it looks like from local:
image

### CODE REVIEW

**Comment by lefou** [comment]
Nice. Is that supposed to work with `mill docs.antora.localPages`? I see the search box, but typing anything in it does not reveal any result or result box.

**Comment by sake92** [comment]
@lefou yes, that screenshot is from my local setup. Not sure why it doesnt work for you, any errors in browser console? Maybe try clean build again.

**Comment by lefou** [comment]
Nothing in console. But I noticed there is no reference to any docsearch script in the page source. Probably an issue in the build, not the browser.

**Comment by lefou** [comment]
Could it be my system is picking another version of antora which doesn't not include the `search-scripts.js` by default? I added it manually, and then it worked for me, too.

Shall I open a PR to your branch?

**Comment by lefou** [comment]
Let's merge this as-is. If it not works out-of-the-box, as it does for you, fine. If not, I can push my fixes afterwards.

**Comment by lefou** [comment]
Thank you!

**Comment by sake92** [comment]
You're welcome! Seems it works fine on the live site. 🥳

**Pull request merged**
