### PR TITLE
Cycle detection in `moduleDeps` and `compileModuleDeps`

### PR DESCRIPTION
**Pull request by lefou**
The problem: We currently don't detect cycles in transitive `moduleDeps` and `compileModuleDeps`. This is results in a `StackOverflowError`.

To solve this, we first need to detect cycles. This is the newly added `Util.recursive` method. Instead of `moduleDeps` we use the `moduleDepsChecked` in some places to ensure we checked for cycles at least once.

Unfortunately, we can't easily report the detected cycle at evaluation time, as `moduleDeps` needs to be evaluated before we can create a task graph (via `T.traverse`), hence we need an alternative way to propagate the exception. The current approach throws an `BuildScriptException` which itself derives from the also new `MillException`. 

In `MillMain`, our central entry point for Mill, we catch `MillException` and report the error to the user.

* Fix https://github.com/com-lihaoyi/mill/issues/2341

### CODE REVIEW

**Comment by lihaoyi** [comment]
I don't think we have any choice but to do it lazily. Scala `object`s are already lazily instantiated, so any error will get thrown during the `resolveTasks` stage, as we collect the necessary tasks, but before evaluation actually starts. Throwing and catching seems like the only way

**Review by lihaoyi — APPROVED** [review]
Looks good to me I think

**Comment by lefou** [comment]
Hm, some tests run way too long and got cancelled. Probably unrelated, restarting them again.

**Comment by lefou** [comment]
Superseded by #2790

**Pull request closed without merging**
