### PR TITLE
Some subediting.

### PR DESCRIPTION
**Pull request by aholland**
- Capitalised Mill in text paragraphs.
 - Put in comments pointing out where double-underscore is used because it is not very clear visually that they are two separate characters.
 - Avoided the use of code style followed by "s" for `plural`s, which did not render well.
 - Changed "&" to "and" in text paragraphs.
 - Minor grammar fixes e.g. for concord.
 Let me know if this is welcome/unwelcome. I don't mind doing it as I read through docs and could do more if wanted. Thanks.

### CODE REVIEW

**Comment by lefou** [comment]
I'd rather wait for merge of #1222, which is almost ready, only release automation is to be done.

**Comment by aholland** [comment]
Oh, absolutely! Those changes look great. Let's see if any of these are still relevant afterwards. Probably not.

**Comment by lefou** [comment]
I think so. I've only applied some conversions and replaced some URLs by variables. With a bit of luck we 'll still get a usable diff.

**Comment by lefou** [comment]
Superseded by #1445.

@aholland I tried to apply most of your edits to the docs. Feel free to review. Thank you!

**Pull request closed without merging**
