### PR TITLE
Deprecate SelectMode.Single and backport evalOrThrow API

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
There is some value in those deprecations, but not all users will recognize them, as Mill up to 0.10.12 is not showing any deprecations for the `build.sc` out of the box. Maybe we can/should change that for 0.10.13. 

Also, I would leave Mill 0.11 out of the descriptions. It doesn't add any clue.

**Comment by lolgab** [comment]
> Also, I would leave Mill 0.11 out of the descriptions. It doesn't add any clue.

The idea was that this is not some kind of deprecation that you can leave there forever, but you need to fix now if you want to migrate.

**Comment by lefou** [comment]
> > Also, I would leave Mill 0.11 out of the descriptions. It doesn't add any clue.
> 
> The idea was that this is not some kind of deprecation that you can leave there forever, but you need to fix now if you want to migrate.

I think we more or less removed all deprecated API in 0.11.

**Comment by lolgab** [comment]
Superseded by https://github.com/com-lihaoyi/mill/pull/2570

**Pull request closed without merging**
