### PR TITLE
Add 2.13.13 and 2.12.19 to supported bridges list

### PR DESCRIPTION
**Pull request by lolgab**
The bridges are already on Maven Central.

Pull Request: https://github.com/com-lihaoyi/mill/pull/3066

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
They aren't needed anywhere except when trying to publish them with the `all` value in `MILL_COMPILER_BRIDGE_VERSIONS` env var, right?

It would be good, if we could set this env var in some CI job, to cover any issues with bridge modules.

**Comment by lolgab** [comment]
No, they are used by mill to decide if try to get the precompiled bridge via coursier, or to compile the bridge in place. With current mill if you use Scala `2.13.13` you see the `Compiling compiler  bridge` log.
Ideally IMO, we would try anyways, and then in case we get a not found from coursier mill should fallback to compile the bridge in place. Otherwise you lose the precompiled bridge if you don't update Mill to the latest snapshot when a new version of Scala is released.

**Comment by lolgab** [comment]
No, they are used by mill to decide if try to get the precompiled bridge via coursier, or to compile the bridge in place. With current mill if you use Scala `2.13.13` you see the `Compiling compiler  bridge` log.
Ideally IMO, we would try anyways, and then in case we get a not found from coursier mill should fallback to compile the bridge in place. Otherwise you lose the precompiled bridge if you don't update Mill to the latest snapshot when a new version of Scala is released.

**Comment by lefou** [comment]
That means, no older Mill version is using the bridges. I also think we should always try to download them.

**Review by lefou — APPROVED** [review]

**Pull request merged**
