### PR TITLE
pythonlib: revert some doc changes

### PR DESCRIPTION
**Pull request by jodersky**
This undoes my last commit of #3998, thereby re-establishing the `ExampleCrossModulePython`. It is required to get some sensible docs for the `basic/` usecase.

However, I'm still not convinced we should share documentation source code between scalalib and pythonlib examples. While it may make sense to share code between JVM technologies, I think python is a completely different beast, and not all concepts translate 1-1. We can see this just with the amount of `find-replaces` there are in `ExampleCrossModulePython` to get the `basic/` example working, and yet the resulting docs still feels off in some places. Also, with so many replacements, the blast radius of scalalib docs becomes unknown: if one day someone makes an innocent change to docs in scalalib, that may have non-sensical results in the python docs.

Preferably, I would like to drop the `ExampleCrossModulePython` and just copy-paste text when necessary, at least until we have a proven pattern of reuse.

### CODE REVIEW

**Comment by jodersky** [comment]
@himanshumahajan138

**Comment by himanshumahajan138** [comment]
@jodersky to be honest when first time i wrote the docs for python examples i didn't used the snippets and upstream inheritances but @lihaoyi pointed out at that time that we should have something like `exampleCrossModuleJava` so after looking at kotlin example i got that idea of creating `exampleCrossModulePython` which extends the upstream java examples and java extends upstream scala examples.


I think @lihaoyi can sought out this...

**Comment by lihaoyi** [comment]
@jodersky @himanshumahajan138 let's go without the example doc sharing for now for Python and leave it separate. We can merge them later if necessary

**Comment by himanshumahajan138** [comment]
> @jodersky @himanshumahajan138 let's go without the example doc sharing for now for Python and leave it separate. We can merge them later if necessary

Ok that's great 💯

**Comment by lihaoyi** [comment]
We can probably close this then

**Pull request closed without merging**
