### PR TITLE
CI: Java 21

### PR DESCRIPTION
**Pull request by lefou**

### CODE REVIEW

**Comment by lefou** [comment]
This failes for scoverage, as scoverage 1.x is not released for any Scala version that is compatible with Java 21.

**Comment by sideeffffect** [comment]
What is blocking the transition to scoverage 2?

**Comment by lefou** [comment]
> What is blocking the transition to scoverage 2?

Mill already suports Scoverage 2! But we also support Scoverage 1.

**Comment by lefou** [comment]
Superseded by https://github.com/com-lihaoyi/mill/pull/3680

**Pull request closed without merging**
