### PR TITLE
Fix TestNg test runner

### PR DESCRIPTION
**Pull request by lihaoyi**
Fixes https://github.com/com-lihaoyi/mill/issues/3798, supersedes https://github.com/com-lihaoyi/mill/pull/3799

Not sure how this ever worked, but it seems like it works now

Converted the example test in https://github.com/com-lihaoyi/mill/pull/3799 to a unit test.

### CODE REVIEW

**Comment by lihaoyi** [comment]
CC @lefou

**Review by lefou — DISMISSED** [review]
Looks good to me. 

Tested with a reasonable large TestNG test suite spawning 98 test processes.

**Comment by lefou** [comment]
@lihaoyi Looks like without custom `testForkGrouping`, the test suite is now running all tests over and over, probably as often as the count of discovered test classes.

**Comment by lihaoyi** [comment]
Ah, we must have been running a single task because that task runs all tests within it for some reason

**Review by lefou — COMMENTED** [review]
Looks good. Local tests seem to work for various fork groups. Thank you for this quick fix!

There is now no longer a single test summary at the end but one for each test class, which is a bit less convenient. Maybe Mill should print a summary, which would look more uniform over the various test frameworks anyways.

**Pull request merged**
