### PR TITLE
Update mill.bat script including some fixes

### PR DESCRIPTION
**Pull request by lefou**

### CODE REVIEW

**Comment by lefou** [comment]
Supersedes #3284

**Review by lihaoyi — APPROVED** [review]

**Comment by lefou** [comment]
It's interesting, that this PR now also shows some build failures in the assembly test. Looks exactly as issue #3283, but with a different reproduction:

* https://github.com/com-lihaoyi/mill/issues/3283

Could be, that we previously always used the mill binary from Github, due to a bug in the script, and the newer version now uses binaries from Maven Central. Maybe they differ?

**Comment by lefou** [comment]
So, I think we discovered that there are more issues in Windows CI then just the assembly test when we now have a fix for. Unfortunately, I already merged this, so we have a failing CI pipeline in `main`.

**Comment by lihaoyi** [comment]
No worries, we can just ignore the windows CI jobs for now and merge regardless

**Pull request merged**
